-- =====================================================================
-- 009_matches.sql
-- Candidate pairings produced by the matching engine.
-- =====================================================================

create table if not exists public.matches (
  id               uuid primary key default gen_random_uuid(),
  lost_report_id   uuid not null references public.lost_reports (id) on delete cascade,
  found_report_id  uuid not null references public.found_reports (id) on delete cascade,
  match_score      numeric(5, 2) not null check (match_score >= 0 and match_score <= 100),
  confidence       text generated always as (
                     case
                       when match_score >= 80 then 'high'
                       when match_score >= 60 then 'medium'
                       else 'low'
                     end
                   ) stored,
  score_breakdown  jsonb not null default '{}'::jsonb,
  status           text not null default 'suggested'
                     check (status in ('suggested', 'viewed', 'claim_started', 'dismissed', 'confirmed')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (lost_report_id, found_report_id)
);

comment on table public.matches is
  'Possible pairings between a lost report and a found report, scored 0-100 by the weighted matching engine (category 20, brand 15, model 15, colour 10, location 15, date 10, time 5, description 10). A match is only a HINT: it never proves ownership and never authorises a handover. Ownership is proven through claims + verification_questions.';
comment on column public.matches.match_score is
  'Weighted similarity score, 0-100. >=80 high confidence, 60-79 medium, <60 low.';
comment on column public.matches.confidence is
  'Derived confidence label, generated by the database so client and admin views always agree.';
comment on column public.matches.score_breakdown is
  'JSON of per-criterion contributions. ADMIN-ORIENTED diagnostic data.';
comment on column public.matches.status is
  'suggested -> viewed -> claim_started -> confirmed, or dismissed by the owner/admin.';

grant select, insert, update on public.matches to authenticated;
grant all on public.matches to service_role;
